services:
  bastos-edi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bastos-edi
    network_mode: "host"
    volumes:
      - bastos-data:/data/bastos
      - ./disk:/app/disk
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  bastos-data:
    driver: local
