services:
  bastos-edi:
    image: bastos-edi
    container_name: bastos-edi
    network_mode: "host"
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - bastos-data:/data/bastos
      - ./disk:/app/disk
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  bastos-data:
    driver: local
